# `Global Superstore — Data Understanding & Audit`

## 1. Setup & Imports

## 2. Load Data

## 3. Initial Inspection
### 3.1 Shape & Schema
### 3.2 Sample Rows (head / tail / sample)

## 4. Missing Value Analysis

## 5. Duplicate Check

## 6. Column-by-Column Audit
### 6.1 Date Columns
### 6.2 Numeric Columns (Sales, Profit, Discount, Quantity, Shipping Cost)
### 6.3 Numeric Columns (Sales, Profit, Discount, Quantity, Shipping Cost)

## 7. Key Finding — Discount vs Profit

## 8. Audit Summary & Cleaning To-Do List

# ___________________________________________________________________________

# `1.IMPORTING LIBRARIES AND SETUP`

In [150]:
import pandas as pd
pd.set_option('display.max_columns', None)

# `2.LOAD DATA`

In [115]:
df=pd.read_csv("../data/raw/Global_Superstore.csv",encoding='latin1')

# `3.Initial Inspection`

## 3.1 Shape & Schema

In [119]:
df.shape

(51290, 24)

In [118]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  str
 2   Order Date      51290 non-null  str
 3   Ship Date       51290 non-null  str
 4   Ship Mode       51290 non-null  str
 5   Customer ID     51290 non-null  str
 6   Customer Name   51290 non-null  str
 7   Segment         51290 non-null  str
 8   City            51290 non-null  str
 9   State           51290 non-null  str
 10  Country         51290 non-null  str
 11  Postal Code     9994 non-null   float64
 12  Market          51290 non-null  str
 13  Region          51290 non-null  str
 14  Product ID      51290 non-null  str
 15  Category        51290 non-null  str
 16  Sub-Category    51290 non-null  str
 17  Product Name    51290 non-null  str
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  str
dtypes: float64(5), int64(2), str(17)
memory usage: 9.4 MB

## 3.2 Sample Rows (head / tail / sample)

In [116]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,Postal Code,Market,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,United States,10024.0,US,East,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,Australia,NaN,APAC,Oceania,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,Australia,NaN,APAC,Oceania,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,Germany,NaN,EU,Central,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,Senegal,NaN,Africa,Africa,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [117]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,Postal Code,Market,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
51285,29002,IN-2014-62366,19-06-2014,19-06-2014,Same Day,KE-16420,Katrina Edelman,Corporate,Kure,Hiroshima,Japan,NaN,APAC,North Asia,OFF-FA-10000746,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,0.01,Medium
51286,35398,US-2014-102288,20-06-2014,24-06-2014,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Houston,Texas,United States,77095.0,US,Central,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,0.01,Medium
51287,40470,US-2013-155768,02-12-2013,02-12-2013,Same Day,LB-16795,Laurel Beltran,Home Office,Oxnard,California,United States,93030.0,US,West,OFF-EN-10001219,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",22.920,3,0.0,11.2308,0.01,High
51288,9596,MX-2012-140767,18-02-2012,22-02-2012,Standard Class,RB-19795,Ross Baird,Home Office,Valinhos,São Paulo,Brazil,NaN,LATAM,South,OFF-BI-10000806,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,0.00,Medium
51289,6147,MX-2012-134460,22-05-2012,26-05-2012,Second Class,MC-18100,Mick Crebagga,Consumer,Tipitapa,Managua,Nicaragua,NaN,LATAM,Central,OFF-PA-10004155,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,0.00,High

In [122]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit,Shipping Cost
count,51290.00000,9994.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000
mean,25645.50000,55190.379428,246.490581,3.476545,0.142908,28.610982,26.375915
std,14806.29199,32063.693350,487.565361,2.278766,0.212280,174.340972,57.296804
min,1.00000,1040.000000,0.444000,1.000000,0.000000,-6599.978000,0.000000
25%,12823.25000,23223.000000,30.758625,2.000000,0.000000,0.000000,2.610000
50%,25645.50000,56430.500000,85.053000,3.000000,0.000000,9.240000,7.790000
75%,38467.75000,90008.000000,251.053200,5.000000,0.200000,36.810000,24.450000
max,51290.00000,99301.000000,22638.480000,14.000000,0.850000,8399.976000,933.570000

# `4. Missing Value Analysis`

In [120]:
df.isnull().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
City                  0
State                 0
Country               0
Postal Code       41296
Market                0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

# `5.Duplicate Check`

In [121]:
print(df.duplicated().sum())

0

In [ ]:
## No Duplicate Rows

# `6. Column-by-Column Audit`

## 6.1 Date Columns

In [125]:
print("Order Date DataType :",df["Order Date"].dtype)
print("Ship Date DataType :",df["Ship Date"].dtype)

Order Date DataType : str
Ship Date DataType : str

In [153]:
## Fixing Date Data Type

In [129]:
df["Order Date"] = pd.to_datetime(df["Order Date"],dayfirst=True)

In [130]:
df["Order Date"].dtype

dtype('<M8[us]')

In [142]:
df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)

In [145]:
print(df['Ship Date'].dtype)

datetime64[us]

In [159]:
df['Order Date'].min(),df['Order Date'].max()

(Timestamp('2011-01-01 00:00:00'), Timestamp('2014-12-31 00:00:00'))

## 6.2 Categorical Columns (Segment, Market, Region, Category, Sub-Category etc.)

In [123]:
l=["Segment","Market","Region","Category","Ship Mode","Order Priority","Sub-Category"]
for i in l:
    print(df[i].value_counts())
    print()

Segment
Consumer       26518
Corporate      15429
Home Office     9343
Name: count, dtype: int64

Market
APAC      11002
LATAM     10294
EU        10000
US         9994
EMEA       5029
Africa     4587
Canada      384
Name: count, dtype: int64

Region
Central           11117
South              6645
EMEA               5029
North              4785
Africa             4587
Oceania            3487
West               3203
Southeast Asia     3129
East               2848
North Asia         2338
Central Asia       2048
Caribbean          1690
Canada              384
Name: count, dtype: int64

Category
Office Supplies    31273
Technology         10141
Furniture           9876
Name: count, dtype: int64

Ship Mode
Standard Class    30775
Second Class      10309
First Class        7505
Same Day           2701
Name: count, dtype: int64

Order Priority
Medium      29433
High        15501
Critical     3932
Low          2424
Name: count, dtype: int64

Sub-Category
Binders        6152
Storage        5059
Art            4883
Paper          3538
Chairs         3434
Phones         3357
Furnishings    3170
Accessories    3075
Labels         2606
Envelopes      2435
Supplies       2425
Fasteners      2420
Bookcases      2411
Copiers        2223
Appliances     1755
Machines       1486
Tables          861
Name: count, dtype: int64

In [175]:
## Categories Check

In [173]:
df["Category"].unique()

<StringArray>
['Technology', 'Furniture', 'Office Supplies']
Length: 3, dtype: str

In [174]:
df["Sub-Category"].unique()

<StringArray>
['Accessories',      'Chairs',      'Phones',     'Copiers',      'Tables',
     'Binders',    'Supplies',  'Appliances',    'Machines',   'Bookcases',
     'Storage', 'Furnishings',         'Art',       'Paper',   'Envelopes',
   'Fasteners',      'Labels']
Length: 17, dtype: str

In [ ]:
# Market Covered

In [165]:
print(list(df['Market'].unique()))

['US', 'APAC', 'EU', 'Africa', 'EMEA', 'LATAM', 'Canada']

## 6.3 Numeric Columns (Sales, Profit, Discount, Quantity, Shipping Cost)

In [ ]:
## Shipping Cost Inspection - Checking impossible values.

In [151]:
df["Shipping Cost"].head()

0    933.57
1    923.63
2    915.49
3    910.16
4    903.04
Name: Shipping Cost, dtype: float64

In [152]:
df["Shipping Cost"].tail()

51285    0.01
51286    0.01
51287    0.01
51288    0.00
51289    0.00
Name: Shipping Cost, dtype: float64

In [154]:
## White Spaces Checks

In [128]:
print(df['Shipping Cost'].apply(lambda x: x != x.strip() if isinstance(x, str) else False).sum())

0

In [155]:
##postal Codes Missing values and Its analysis

In [126]:
df[df['Postal Code'].isnull()]['Country'].value_counts()

Country
Australia      2837
France         2827
Mexico         2644
Germany        2065
China          1880
               ...
South Sudan       2
Bahrain           2
Swaziland         2
Burundi           2
Eritrea           2
Name: count, Length: 146, dtype: int64

In [149]:
print((df['Country'] != 'United States').sum())

41296

In [156]:
##Profit Analysis

In [131]:
df['Profit'].describe()

count    51290.000000
mean        28.610982
std        174.340972
min      -6599.978000
25%          0.000000
50%          9.240000
75%         36.810000
max       8399.976000
Name: Profit, dtype: float64

In [132]:
print((df['Profit'] < 0).sum())

12544

In [136]:
print(df[df['Profit'] < 0]['Discount'].mean())

0.450811862244898

In [137]:
print(df[df['Profit'] > 0]['Discount'].mean())

0.043320394978727875

In [133]:
print((df['Profit'] < 0).mean() * 100)

24.457009163579645

In [134]:
print(df['Discount'].min(), df['Discount'].max())

0.0 0.85

In [157]:
## Checking Impossible Values in Relation with Sales , quantity and Shipping cost

In [135]:
df[['Sales','Quantity','Shipping Cost']].describe()

              Sales      Quantity  Shipping Cost
count  51290.000000  51290.000000   51290.000000
mean     246.490581      3.476545      26.375915
std      487.565361      2.278766      57.296804
min        0.444000      1.000000       0.000000
25%       30.758625      2.000000       2.610000
50%       85.053000      3.000000       7.790000
75%      251.053200      5.000000      24.450000
max    22638.480000     14.000000     933.570000